### ISSUE TITLE
Immediately Engaging (Cycle 1)

### ISSUE THREAD

**Issue by forgottenboy** [forgottenboy/bydesign#3]
## Q3 2017 Initiative: 
Both new & returning users have an engaging experience the moment they land in Looker.

## Project Goals: 
- Create a landing page that includes suggested content for the user who is viewing the page
- Explain why that content is relevant to that user
- Be more engaging than our existing homepage

## Tasks
- [ ] Strip Existing Homepage https://github.com/looker/helltool/issues/30247
- [ ] Finalize a Couple Design nits https://github.com/looker/helltool/issues/30248
- [ ] Update Layout to Match New Designs https://github.com/looker/helltool/issues/30249
- [ ] Update Tiles to Match New Designs https://github.com/looker/helltool/issues/30250
- [ ] Implement "Suggested For You" in future Dream World https://github.com/looker/helltool/issues/30251
- [ ] Apply Data-less Thumbnails to the Suggested Content Module https://github.com/looker/helltool/issues/30256

## Successful?
- Positive feedback from metanew users on updated layout and the content they see there
- Users click on content they see on landing page
